package lk.ijse.aad.backend.entity;

import jakarta.persistence.*;
import lk.ijse.aad.backend.enums.PaymentMethod;
import lk.ijse.aad.backend.enums.PaymentStatus;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "payments")
@Getter
@Setter
@NoArgsConstructor   // Required by JPA: creates a no-argument constructor
@ToString
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // Primary key for the payment table (auto-incremented)
    private Long id;

    // Each payment is linked to exactly one booking
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "booking_id", nullable = false)
    private Booking booking;

    // The user who made the payment
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // Payment method used (CARD, CASH, ONLINE, etc.)
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PaymentMethod paymentMethod;

    // Payment status (default is PENDING)
    // The service layer will update this to COMPLETED or FAILED
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PaymentStatus status = PaymentStatus.PENDING;

    // Amount paid for the booking
    // precision=10, scale=2 allows values like 99999999.99
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal amount;

    // Currency used for the payment (default is Sri Lankan Rupees)
    @Column(nullable = false, length = 10)
    private String currency = "LKR";

    // Card holder name (only used when payment method is CARD)
    private String cardName;

    // Masked card number (example: **** **** **** 1234)
    // Never store the full card number for security reasons
    private String cardNumber;

    // Card expiry date (MM/YY format)
    private String expiryDate;

    // CVV code – should always be stored masked or encrypted
    private String cvv;

    // Unique transaction reference generated by the system
    // Example: TXN-A1B2C3D4E5F6
    @Column(unique = true)
    private String transactionId;

    // Automatically stores the date and time when the payment record is created
    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;
}